version: '3'
services:
  golangcrud:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_USER_DB=users
      - JWT_SECRET_KEY=JUFAIJFUSIAHUGIABNGASYUGBAS*&@764367436287HUYBFASFANFHDNA
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - meu_crud_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - meu_crud_network

networks:
  meu_crud_network:
